Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.box_check_update = false
  config.ssh.insert_key = false
  config.vm.provision "ssh", type: "shell", inline: "echo Installing sshpass; apt-get install -y sshpass"

  config.vm.define "jenkins" do |subconfig|
    subconfig.vm.provider "virtualbox" do |vb|
      vb.name = "jenkinsmaster"
      vb.memory = 1024
      vb.cpus = 1
    end
    subconfig.vm.hostname = "jenkinsmaster"
    subconfig.vm.network "private_network", ip: "192.168.53.3"
  end

  config.vm.define "build" do |subconfig|
    subconfig.vm.provider "virtualbox" do |vb|
      vb.name = "build"
      vb.memory = 1024
      vb.cpus = 1
    end
    subconfig.vm.hostname = "build"
    subconfig.vm.network "private_network", ip: "192.168.53.4"
  end
  
  config.vm.define "deploy" do |subconfig|
    subconfig.vm.provider "virtualbox" do |vb|
      vb.name = "deploy"
      vb.memory = 1024
      vb.cpus = 1
    end
    subconfig.vm.hostname = "deploy"
    subconfig.vm.network "private_network", ip: "192.168.53.5"
  end
end
