Vagrant.configure(2) do |config|
  
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "bento/ubuntu-20.04"
    jenkins.vm.provider :hyperv do |jenkins_master|
      jenkins_master.vmname = "jenkinsmaster"
      jenkins_master.memory = 2048
      jenkins_master.cpus = 1 
    end
    jenkins.vm.hostname = "jenkinsmaster"
    jenkins.vm.network "public_network" 
  end 

  config.vm.define "build" do |build|
    build.vm.box = "bento/ubuntu-20.04"
    build.vm.provider :hyperv do |build_server|
      build_server.vmname = "buildserver"
      build_server.memory = 3072
      build_server.cpus = 2
    end
    build.vm.hostname = "buildserver"
    build.vm.network "public_network" 
  end 

  config.vm.define "deploy" do |deploy|
    deploy.vm.box = "bento/ubuntu-20.04"
    deploy.vm.provider :hyperv do |deploy_sever|
      deploy_sever.vmname = "deployserver"
      deploy_sever.memory = 2048
      deploy_sever.cpus = 1
    end
    deploy.vm.hostname = "deployserver"
    deploy.vm.network "public_network" 
  end 

  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'

  config.vm.synced_folder ".", "/vagrant", disabled: true

end
