---
- name: Install Jenkins
  hosts: jenkins_master
  become: True
  tasks:
    - name: Download jenkins.war
      get_url:
        url: https://get.jenkins.io/war-stable/2.263.4/jenkins.war
        dest: /home/vagrant/

    - name: Install java
      apt:
        name: default-jre
        update_cache: yes

    - name: Copy service file
      copy:
        content: "{{ lookup('file', 'jenkins_master.service') }}"
        dest: /etc/systemd/system/jenkins_master.service

    - name: Restart unit file
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: jenkins_master.service

    - name: Started jenkins service
      ansible.builtin.service:
        name: jenkins_master.service
        state: started

    - name: Waiting for init password
      shell:
        cmd: sleep 30

    - name: Get init password
      shell:
        cmd: cat /root/.jenkins/secrets/initialAdminPassword
      register: admin_pass

    - debug:
        msg: "{{ admin_pass['stdout'] }}"
