pipeline {
    agent { label 'deploy' }

    stages {
        stage('Prepare') {
            steps {
                sh 'sudo docker stop wiki_container | exit 0'
                sh 'sudo docker rm wiki_container | exit 0'
            }
        }
        stage('Pull') {
            steps {
                sh 'sudo docker pull 192.168.53.4:5000/python_wiki'
         
            }
        }    
        stage('Run') {
            steps {
                sh 'sudo docker run -dp 5000:5000 --name wiki_container 192.168.53.4:5000/python_wiki'
            }
        }
        
    }
}
